config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers:{
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }
  get 'pages/home'

  get 'pages/index'

  get 'pages/home_admin' => 'pages#home_admin'

  resources :tipo_servicios
  resources :datos_personals
  resources :servicios
  resources :animal_adoptars
  resources :animal_adoptar_fotos

  get 'datos_personals/obtener_ciudades/:id' => 'datos_personals#obtener_ciudades'
  
  root 'pages#home' #controlador pages, action home

end

app/models/tipo_servicio.rb
class TipoServicio < ActiveRecord::Base
	has_many :servicios

	validates :nombre, :presence => {:message => "Debe colocar el nombre del servicio"}
	validates :descripcion, :presence => {:message => "Debe colocar la descripcion del servicio"}

	def datos
		"#{nombre} : #{descripcion}"
	end
end

app/controllers/tipo_servicios_controller.rb
class TipoServiciosController < ApplicationController
  before_action :set_tipo_servicio, only: [:show, :edit, :update, :destroy]

  # GET /tipo_servicios
  # GET /tipo_servicios.json
  def index
    @tipo_servicios = TipoServicio.all
  end

  # GET /tipo_servicios/1
  # GET /tipo_servicios/1.json
  def show
  end

  # GET /tipo_servicios/new
  def new
    @tipo_servicio = TipoServicio.new
  end

  # GET /tipo_servicios/1/edit
  def edit
  end

  # POST /tipo_servicios
  # POST /tipo_servicios.json
  def create
    @tipo_servicio = TipoServicio.new(tipo_servicio_params)

    respond_to do |format|
      if @tipo_servicio.save
        format.html { redirect_to @tipo_servicio, notice: 'Tipo servicio was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_servicio }
      else
        format.html { render :new }
        format.json { render json: @tipo_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_servicios/1
  # PATCH/PUT /tipo_servicios/1.json
  def update
    respond_to do |format|
      if @tipo_servicio.update(tipo_servicio_params)
        format.html { redirect_to @tipo_servicio, notice: 'Tipo servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_servicio }
      else
        format.html { render :edit }
        format.json { render json: @tipo_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_servicios/1
  # DELETE /tipo_servicios/1.json
  def destroy
    @tipo_servicio.destroy
    respond_to do |format|
      format.html { redirect_to tipo_servicios_url, notice: 'Tipo servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_servicio
      @tipo_servicio = TipoServicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_servicio_params
      params.require(:tipo_servicio).permit(:nombre, :descripcion)
    end
end

app/helpers/tipo_servicios_helper.rb
module TipoServiciosHelper
end

app/views/tipo_servicios/_form.html.erb
<%= simple_form_for(@tipo_servicio) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tipo_servicios/edit.html.erb
<h1>Editing Tipo Servicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_servicio %> |
<%= link_to 'Back', tipo_servicios_path %>

app/views/tipo_servicios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tipo Servicios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_servicios.each do |tipo_servicio| %>
      <tr>
        <td><%= tipo_servicio.nombre %></td>
        <td><%= tipo_servicio.descripcion %></td>
        <td><%= link_to 'Show', tipo_servicio %></td>
        <td><%= link_to 'Edit', edit_tipo_servicio_path(tipo_servicio) %></td>
        <td><%= link_to 'Destroy', tipo_servicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo servicio', new_tipo_servicio_path %>

app/views/tipo_servicios/new.html.erb
<h1>New Tipo Servicio</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_servicios_path %>

app/views/tipo_servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_servicio.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tipo_servicio.descripcion %>
</p>

<%= link_to 'Edit', edit_tipo_servicio_path(@tipo_servicio) %> |
<%= link_to 'Back', tipo_servicios_path %>