config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers:{
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }
  get 'pages/home'

  get 'pages/index'

  get 'pages/home_admin' => 'pages#home_admin'

  resources :tipo_servicios
  resources :datos_personals
  resources :servicios
  resources :animal_adoptars
  resources :animal_adoptar_fotos

  get 'datos_personals/obtener_ciudades/:id' => 'datos_personals#obtener_ciudades'
  
  root 'pages#home' #controlador pages, action home

end

app/models/animal_adoptar.rb
class AnimalAdoptar < ActiveRecord::Base
	has_many :animal_adoptar_fotos, dependent: :destroy

	accepts_nested_attributes_for :animal_adoptar_fotos, reject_if: proc {|attributes| attributes['imagen'].blank?},allow_destroy: true #pa que lleve foto

	validates :tipo, :presence => {:message => "Debe seleccionar el tipo: PERRO o GATO"}
	validates :raza, :presence => {:message => "Debe indicar la raza del perro"}
	validates :genero, :presence => {:message => "Debe seleccionar el genero"}
	validates :descripcion, :presence => {:message => "Debe escribir una descripción"}
	validates :edad, :presence => {:message => "Debe colocar la edad aproximada"}
end

app/controllers/animal_adoptars_controller.rb
class AnimalAdoptarsController < ApplicationController
  before_action :set_animal_adoptar, only: [:edit, :update, :destroy]

  include CodigosGenerales
  before_action :cargarOpcionesDelMenuServicios

  def index
    @animal_adoptars = AnimalAdoptar.all.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @animal_adoptar = AnimalAdoptar.find(params[:id])
  end

  def new
    @animal_adoptar = AnimalAdoptar.new
    @animal_adoptar.animal_adoptar_fotos.build #pa las fotos
  end

  def create
    @animal_adoptar = AnimalAdoptar.new(animal_adoptar_params)

    respond_to do |format|
      if @animal_adoptar.save
        format.html { redirect_to @animal_adoptar, notice: 'Animal creado exitosamente.' }
        format.json { render :show, status: :created, location: @animal_adoptar }
      else
        format.html { render :new }
        format.json { render json: @animal_adoptar.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @animal_adoptar.animal_adoptar_fotos.build
  end

  def update
    respond_to do |format|
      if @animal_adoptar.update(animal_adoptar_params)
        format.html { redirect_to @animal_adoptar, notice: 'Animal adoptar was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal_adoptar }
      else
        format.html { render :edit }
        format.json { render json: @animal_adoptar.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @animal_adoptar.destroy
    respond_to do |format|
      format.html { redirect_to animal_adoptars_url, notice: 'Animal adoptar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_animal_adoptar
    @animal_adoptar = AnimalAdoptar.find(params[:id])
  end
  def animal_adoptar_params
    params.require(:animal_adoptar).permit(:tipo, :raza, :genero, :edad, :descripcion, animal_adoptar_fotos_attributes:[:id, :imagen, :destroy])
  end
end

app/helpers/animal_adoptars_helper.rb
module AnimalAdoptarsHelper
end

app/views/animal_adoptars/_form.html.erb
 <br />
        <div class="row">
          <div class="col-lg-3"></div>
          <div class="col-lg-6">

<div class="panel panel-primary"> 
<div class=panel-heading> <h3 class=panel-title>Agregar adopción</h3> </div>
 <div class=panel-body> 

<%= simple_form_for@animal_adoptar, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>

    <% if @animal_adoptar.errors.any? %>
    <div class="alert alert-danger">
       <div class="error_explanation">
          <ul>
             <% @animal_adoptar.errors.each do |attr,msg| %>
             <li><%= "#{msg}" if @animal_adoptar.errors[attr].first == msg %> </li>
             <% end %>
          </ul>
       </div>
    </div>
    <% end %>


  <div class="form-group">
      <div class="col-lg-8">
        <%= f.label :sexo %>
        <%=f.collection_radio_buttons :tipo, [["Gato", 'Gato'] ,["Perro", 'Perro']], :first, :last %>
      </div>  
  </div>

  <div class="form-group">
   <label class="control-label col-lg-4" >*Raza</label>
    <div class="col-lg-6">
    <%= f.input :raza, label: false, placeholder: "Coloque la raza del animal", wrapper_html: { class: 'username' } %> 
    </div>
  </div>
       
 <div class="form-group">
      <div class="col-lg-8">
         <%= f.label :genero %>
        <%=f.collection_radio_buttons :genero, [["Macho", 'Hembra'] ,["Macho", 'Hembra']], :first, :last %>
      </div> 
</div>
 <div class="form-group">

      <div class="col-lg-8">
         <%= f.label :edad %>
         <%= f.input :edad, label: false, placeholder: "Coloque la edad aproximada del animalito" %>
      </div> 
</div>
 <div class="form-group">
       <div class="col-lg-8">
        <%= f.input :descripcion, as: :text, label: 'Breve descripción:', placeholder: "Coloque una breve descripción del animalito" %>
       </div>
  </div>

  <h2> Fotos </h2>
  <%= f.fields_for :animal_adoptar_fotos do |foto| %>
      <div class="form-group">
        <%=foto.label :imagen, class: "control-label col-lg-2"%>
        <div class="col-lg-6">
          <%=foto.text_field :imagen%>
          <%=foto.check_box :_destroy%>
          <%=foto.label "Eliminar"%>                               
        </div>
      </div>
  <%end%>  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/animal_adoptars/create.html.erb
<h1>AnimalAdoptars#create</h1>
<p>Find me in app/views/animal_adoptars/create.html.erb</p>

app/views/animal_adoptars/destroy.html.erb
<h1>AnimalAdoptars#destroy</h1>
<p>Find me in app/views/animal_adoptars/destroy.html.erb</p>

app/views/animal_adoptars/edit.html.erb
<h1>Editing Aninal Adoptar</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal_adoptar %> |
<%= link_to 'Back', animal_adoptars_path %>

app/views/animal_adoptars/index.html.erb
<p id="notice"><%= notice %></p>



<br/>
<%if !@animal_adoptars.empty? %>
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">Listado de animales en adopción</div>
      <div class="table-responsive" style="height:260px" >
        <table class="table table-striped table-hover table-bordered" >
          <thead >
            <tr >
              <th>tipo</th>
              <th>raza</th>
              <th>genero</th>
               <th>edad</th>
              <th>descripción</th>
             
              <th style="text-align: center">Ver</th>
              <th style="text-align: center">Editar</th>
              <th style="text-align: center">Eliminar</th>
            </tr>
          </thead>
          <tbody style="overflow-y: scroll;height: auto; width:100%">
          <% @animal_adoptars.each do |dato| %>
           
            <tr>
              <td><%=dato.tipo%></td>
              <td><%=dato.raza%></td>
              <td><%=dato.genero%></td>
              <td><%=dato.edad%></td>
              <td><%=dato.descripcion%></td>
              <td><%= link_to 'Show', animal_adoptar_path(dato) %></td>
              <td>
                <div align="center">
                  <%=link_to edit_animal_adoptar_path(dato),
                    title: 'Editar',
                    'data-toggle' => 'tooltip','data-placement' => 'right' do %>
                  <span class="fa fa-fw fa-pencil"></span>
                  <%end%>
                </div>
              </td>
              <td>

                <div align="center">
                  <%=link_to  animal_adoptar_path(dato), method: :delete, 
                    title: 'Eliminar los datos personales',
                    'data-toggle' => 'tooltip','data-placement' => 'right',
                    data: { confirm: 'Esta seguro que desea eliminar los datos personales' }  do %>
                  <span class="fa fa-fw fa-trash-o"></span>
                  <%end%>
                </div>
              </td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
    <%= will_paginate @animal_adoptars,  renderer: BootstrapPagination::Rails %>
  </div>
  <div class="col-lg-3"></div>
</div>

<%end%>

<div class="row">
  <div class="col-md-4 col-md-offset-5">
  <%=link_to "Agregar nueva adopción", new_animal_adoptar_path %>
  
  </div>
</div>

app/views/animal_adoptars/new.html.erb
<h1>Nueva animal para adopción</h1>

<%= render 'form' %>

<%= link_to 'Back', animal_adoptars_path %>

app/views/animal_adoptars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @animal_adoptar.tipo %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @animal_adoptar.raza %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @animal_adoptar.genero %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @animal_adoptar.descripcion %>
</p>

<h2> Fotos </h2>
<% if @animal_adoptar.animal_adoptar_fotos.any? %>
  <ul>
  <%@animal_adoptar.animal_adoptar_fotos.each do |foto|%>
  <li><%=link_to foto, foto%></li>
  <%end%>
  </ul>  
<%else%>
<p> No existen fotos almacenadas</p>

<%end%>

<%= link_to 'Edit', edit_animal_adoptar_path(@animal_adoptar) %> |
<%= link_to 'Back', animal_adoptars_path %>

app/views/animal_adoptars/update.html.erb
<h1>AnimalAdoptars#update</h1>
<p>Find me in app/views/animal_adoptars/update.html.erb</p>