config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers:{
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }
  get 'pages/home'

  get 'pages/index'

  get 'pages/home_admin' => 'pages#home_admin'

  resources :tipo_servicios
  resources :datos_personals
  resources :servicios
  resources :animal_adoptars
  resources :animal_adoptar_fotos

  get 'datos_personals/obtener_ciudades/:id' => 'datos_personals#obtener_ciudades'
  
  root 'pages#home' #controlador pages, action home

end

app/models/datos_personal.rb
class DatosPersonal < ActiveRecord::Base
	validates :nombre, :presence => {:message => "Debe colocar su nombre completo"}
	validates :apellido, :presence => {:message => "Debe colocar su apellido completo"}

	validates :ciudad, :presence => {:message => "Debe colocar la ciudad donde vive"}
	validates :estado, :presence => {:message => "Debe colocar el estado donde se encuentra"}

	validate :sexo, :validar_sexo

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


	validate :presencia_de_algun_telefono                

#scope :publicado, lambda { where("servicios.nombre IS NOT NULL") } 

def validar_sexo
	if self.sexo==nil
		errors.add(:sexo, "Debe seleccionar su sexo")
	end
end

def presencia_de_algun_telefono
	if [self.telefono, self.celular].reject(&:blank?).size == 0
		errors.add(:telefono1, "Debe colocar al menos un teléfono de contacto")
	end 
end


def estados_venezolanos
	[
		'Amazonas', 
		'Anzoategui', 
		'Apure',
		'Aragua',
		'Barinas',
		'Bolívar',
		'Carabobo',
		'Cojedes',
		'Guarico',
		'Delta Amacuro',
		'Dependencia Federal',
		'Distrito Capital Caracas',
		'Falcon',
		'Lara',
		'Margarita',
		'Merida',
		'Miranda',
		'Monagas',
		'Portuguesa',
		'Sucre',
		'Tachira',
		'Trujillo',
		'Vargas',
		'Yaracuy',
		'Zulia'
	]
end

#al colocar self hace que el método sea un método de clase por lo que no necesito instanciar entre otras cosas
def self.estados_ciudades_venezolanos_hash
    {
    'Amazonas' => {},
    'Anzoategui' => {},
    'Apure' => {capital: "San Fernando de Apure", municipios: ['Achaguas', 'Biruaca', 'Muñoz', 'Páez', 'Pedro Camejo', 'Rómulo Gallegos', 'San Fernando'] },
    'Aragua' => {capital: "Maracay", municipios: ['Bolívar', 'Camatagua', 'Francisco Linares Alcántara', 'Girardot', 'José Ángel Lamas', 'José Félix Ribas', 'José Rafael Revenga', 'Libertador', 'Mario Briceño Iragorry', 'Ocumare de la Costa de Oro', 'San Casimiro', 'San Sebastián', 'Santiago Mariño', 'Santos Michelena', 'Sucre, Tovar', 'Urdaneta', 'Zamora'] },
    'Barinas' => {},
    'Bolívar' => {},
    'Carabobo' => {},
    'Cojedes' => {},
    'Guarico' => {},
    'Delta Amacuro' => {},
    'Dependencia Federal' => {},
    'Distrito Capital' =>{capital: "Caracas", municipios: ['Libertador']},
    'Falcon' => {},
    'Lara' => {},
    'Maragarita' => {},
    'Merida' => {},
    'Miranda' => {capital: "Los Teques", municipios: ['Baruta', 'Chacao', 'Sucre', 'Hatillo']},
    'Monagas' => {},
    'Nueva Esparta' => {capital: "La Asunción", municipios: ['Antolín del Campo', 'Arismendi', 'Díaz', 'García', 'Gómez', 'Maneiro', 'Marcano', 'Mariño', 'Península de Macanao', 'Tubores', 'Villalba']},
    'Portuguesa' => {},
    'Sucre' => {},
    'Tachira' => {},
    'Trujillo' => {},
    'Vargas' => {},
    'Yaracuy' => {},
    'Zulia'=> {}
    }
 
end

end

app/controllers/datos_personals_controller.rb
class DatosPersonalsController < ApplicationController
  before_action :set_datos_personal, only: [:show, :edit, :update, :destroy]
  
  include CodigosGenerales
  before_action :cargarOpcionesDelMenuServicios

  def index
    @datos_personals = DatosPersonal.all.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @datos_personal = DatosPersonal.new
    @ciudades = []

  end

  def create
    #puts params[:datos_personal][:nombre]
    #render :text => params[:datos_personal].inspect
    @datos_personal = DatosPersonal.new(datos_personal_params)
    @ciudades = []
    respond_to do |format|
      if @datos_personal.save
        format.html { redirect_to @datos_personal, notice: 'Datos personales agregados exitosamente.' }
        format.json { render :show, status: :created, location: @datos_personal }
      else
        format.html { render :new }
        format.json { render json: @datos_personal.errors, status: :unprocessable_entity }
      end
  end
#Inteligencia colectiva
end

def edit
  @datos_personals = DatosPersonal.find(params[:id])
  @ciudades = []
end

def update
  @ciudades = []
  respond_to do |format|
    if @datos_personal.update(datos_personal_params)
      format.html {redirect_to @datos_personal, notice: 'Sus datos se modificaron exitosamente'}
      format.json {render :show, status: :ok, location: @datos_personal}
    else
      format.html {render :edit}
      format.json {render json: @datos_personals.errors, status: :unprocessable_entity}
    end
  end
end

def destroy
end

def show
end

def set_datos_personal
  @datos_personal = DatosPersonal.find(params[:id])
end

def datos_personal_params
  params.require(:datos_personal).permit(:nombre, :apellido, :fecha_nacimiento, :sexo, :telefono, :celular, :direccion, :estado, :ciudad, :calificacion, :correo_alternativo)
end

def obtener_ciudades
  @ciudades = DatosPersonal.estados_ciudades_venezolanos_hash[params[:estado_id]][:municipios].insert(0,DatosPersonal.estados_ciudades_venezolanos_hash[params[:estado_id]][:capital])
end
end

app/helpers/datos_personals_helper.rb
module DatosPersonalsHelper
end

app/views/datos_personals/_form.html.erb
  <br />
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">

      <div class="panel panel-primary"> 
        <div class=panel-heading> <h3 class=panel-title><%=labelBoton%> datos personales</h3> </div>
        <div class=panel-body> 
          
          <%= simple_form_for @datos_personal, html: { class: 'form-horizontal' },
          wrapper: :horizontal_form do |f| %>

          <%= f.error_notification %>

          <% if @datos_personal.errors.any? %>

          <div class="alert alert-danger">
           <div class="error_explanation">
            <ul>
             <% @datos_personal.errors.each do |attr,msg| %>
             <li><%= "#{msg}" if @datos_personal.errors[attr].first == msg %> </li>
             <% end %>
           </ul>
         </div>
       </div>
       <% end %>


       <div class="form-group">
        <div class="col-lg-8">
         <%= f.input :nombre, label: 'Nombre', placeholder: "Nombre completo" %>
       </div>odificar datos personales
       <div class="col-lg-8">
         <%= f.input :apellido, label: 'Apellido', placeholder: "Apellido completo" %>
       </div>
       <div class="col-lg-10">
         <%= f.input :fecha_nacimiento, label: 'Fecha de nacimiento' %>
       </div>
       <div class="col-lg-8">
         <%= f.label :sexo %>
         <%=f.collection_radio_buttons :sexo, [[true, 'Masculino'] ,[false, 'Femenino']], :first, :last %>
       </div>

       <div class="col-lg-8">
         <%= f.input :telefono, label: 'Telefono local', placeholder: "Coloque un teléfono local" %>
       </div>
       <div class="col-lg-8">
         <%= f.input :celular, label: 'Celular', placeholder: "Coloque su teléfono celular" %>
       </div>
       <div class="col-lg-8">
         <%#= f.input :estado, label: 'Estado', placeholder: "Coloque el estado donde vive" %>
         <%= f.input :estado, :collection => @datos_personal.estados_venezolanos, input_html: {class:'estado_seleccionado'} %>

       </div>
       <div class="col-lg-8">
         <%#= f.input :ciudad, label: 'Ciudad', placeholder: "Coloque la ciudad donde vive" %>
         <%= f.input :ciudad, :collection=>@ciudades,input_html:{class:'coleccion_ciudades'} %>
       </div>
       <div class="col-lg-8">
         <%= f.input :direccion, as: :text, label: 'Dirección de habitación', placeholder: "Coloque la dirección donde vive" %>
       </div>
       <div class="col-lg-8">
         <%= f.input :correo_alternativo, label: 'Correo alternativo', placeholder: "Correo alternativo" %>
       </div>

       <div class="col-lg-8">
        <%=f.input :calificacion, collection: 18..60, prompt: "Select your age", selected: 21%>
      </div>

      <%#= f.input :estados, collection: DatosPersonal::ESTADOS %>
      
    </div>
    
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.button :submit, labelBoton, :class=> "btn btn-primary" %>
      </div>
    </div>
    <%end%>

  </div> 
</div> 

</div>
<div class="col-lg-3"></div>
</div>

app/views/datos_personals/edit.html.erb
<%=render 'form', labelBoton: "Modificar" %>

app/views/datos_personals/index.html.erb
<br/>
<%if !@datos_personals.empty? %>
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">Listado de datos personales</div>
      <div class="table-responsive" style="height:260px" >
        <table class="table table-striped table-hover table-bordered" >
          <thead >
            <tr >
              <th>Nombre</th>
              <th>Apellido</th>
              <th style="text-align: center">Ver</th>
              <th style="text-align: center">Editar</th>
              <th style="text-align: center">Eliminar</th>
            </tr>
          </thead>
          <tbody style="overflow-y: scroll;height: auto; width:100%">
            <% @datos_personals.each do |dato| %>
            <tr>
              <td><%=dato.nombre%></td>
              <td><%=dato.apellido%></td>
              <td></td>
              <td>
                <div align="center">
                  <%=link_to edit_datos_personal_path(dato),
                    title: 'Editar los datos personales',
                    'data-toggle' => 'tooltip','data-placement' => 'right' do %>
                  <span class="fa fa-fw fa-pencil"></span>
                  <%end%>
                </div>
              </td>
              <td>
                <div align="center">
                  <%=link_to  datos_personal_path(dato), method: :delete, 
                    title: 'Eliminar los datos personales',
                    'data-toggle' => 'tooltip','data-placement' => 'right',
                    data: { confirm: 'Esta seguro que desea eliminar los datos personales' }  do %>
                  <span class="fa fa-fw fa-trash-o"></span>
                  <%end%>
                </div>
              </td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
    <%= will_paginate @datos_personals,  renderer: BootstrapPagination::Rails %>
  </div>
  <div class="col-lg-3"></div>
</div>

<%end%>

<div class="row">
  <div class="col-md-4 col-md-offset-5">
  <%=link_to "Agregar Datos personales", new_datos_personal_path %>
  
  </div>
</div>

app/views/datos_personals/new.html.erb
<h1>Agregar datos personales</h1>
<%=render 'form', labelBoton: "Agregar" %>
<%=link_to 'Echar pa atras',datos_personals_path %>

app/views/datos_personals/obtener_ciudades.js.erb
<%puts @ciudades%>
$('.coleccion_ciudades').empty();

$('.coleccion_ciudades').append( $('<option>Select la ciudad</option>'));

<% @ciudades.each do |ciudad| %>
  	$('#datos_personal_ciudad').append($('<option value="<%= ciudad%>"><%= ciudad %></option>'));
<% end %>

app/views/datos_personals/show.html.erb
  <br />
  
  <div id="page-wrapper">
    <div class="container-fluid">
      <!-- Page Heading -->
      <div class="row">
        <div class="col-lg-12">
          <% flash.each do |key, value| %>
          <div class="alert alert-success fade in">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <strong><%=value%></strong>
          </div>
          <% end %>
        </div>
      </div><!-- /.row -->

      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-5">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title"></h3>
              <div style="text-align: center">
                <h3 class="panel-title">Datos personales</h3>
              </div>
            </div>
            <div class="panel-body">
              <ul class="list-group">
                <li class="list-group-item"><strong>Nombre:</strong>
                  <%=@datos_personal.nombre%>
                </li>
                <li class="list-group-item"><strong>Apellido:</strong>
                  <%=@datos_personal.apellido%>
                </li>
                <li class="list-group-item"><strong>Fecha nacimiento:</strong>
                  <%=humanizar_fecha_corta @datos_personal.fecha_nacimiento%>
                </li>
                <% puts @datos_personal.sexo%>
                <li class="list-group-item"><strong>Sexo:</strong>
                  <%= humanizar_sexo @datos_personal.sexo%>
                </li>
                <li class="list-group-item"><strong>Teléfono:</strong>
                  <%=@datos_personal.telefono%>
                </li>
                <li class="list-group-item"><strong>Celular:</strong>
                  <%=@datos_personal.celular%>
                </li>
                <li class="list-group-item"><strong>Estado:</strong>
                  <%=@datos_personal.estado%>
                </li>
                <li class="list-group-item"><strong>Ciudad:</strong>
                  <%=@datos_personal.ciudad%>
                </li>
                <li class="list-group-item"><strong>Dirección:</strong>
                  <%=@datos_personal.direccion%>
                </li>
                <li class="list-group-item"><strong>Correo alternativo:</strong>
                  <%=@datos_personal.correo_alternativo%>
                </li>
                <li class="list-group-item"><strong>Calificación:</strong>
                  <%=@datos_personal.calificacion%>
                </li>
                
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-3"></div>  
      </div>
      <!-- /.row -->

      <div class="row">
       <div class="col-lg-3"></div>
       <div class="col-lg-6">
        <div align="center">
         <%= link_to 'Modificar', edit_datos_personal_path(@datos_personal) %> |
         <%= link_to 'Regresar', datos_personals_path %>

       </div>
       <div>
        <div class="col-lg-3"></div>
      </div><!-- /.row -->

    </div><!-- /.container-fluid -->
    </div><!-- /#page-wrapper -->