config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers:{
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }
  get 'pages/home'

  get 'pages/index'

  get 'pages/home_admin' => 'pages#home_admin'

  resources :tipo_servicios
  resources :datos_personals
  resources :servicios
  resources :animal_adoptars
  resources :animal_adoptar_fotos

  get 'datos_personals/obtener_ciudades/:id' => 'datos_personals#obtener_ciudades'
  
  root 'pages#home' #controlador pages, action home

end

app/views/shared/_footer.html.erb
<div class="contenedor">
        <p class="copy">Casigatos &copy; 2016</p>
        <div class="sociales">
            <a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a  href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
        </div>
    </div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    

    <div class="contenedor">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Adopta una mascota</a>
      </div>


      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Inicio</a></li>
          <li><a href="#">Adopta un perrito</a></li>
          <li><a href="#">Adopta un gatico</a></li> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Servicios <span class="caret"></span></a>

            <%if @tipo_servicios.length !=0 %>       
            <ul class="dropdown-menu">
              <%@tipo_servicios.each do |enlace|%>         
              <li ><a class="list-group-item" href="#" ><%=enlace.nombre%></a></li>
              <%end%>
            </ul>
            <%end%>            
          </li>        
        <!--li>
          <%=link_to new_usuario_session_path do %>
          <i class="fa fa_user"></i>Ingresar<%end%>
        </li--> 
        <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i>Contactenos</a></li>   
        <%if !current_usuario%> <li>

        <%=link_to new_usuario_session_path do %> <i class="fa fa-user"></i>Ingresar

        <%end%> </li>

        <% else %>
        <li><a href="#">Hola <%=current_usuario.email%></a></li> <li>

        <%=link_to destroy_usuario_session_path, method: :delete do %> <i class="fa fa-user"></i>Salir

        <%end%> </li>

        <%end%> 
      </ul>
    </div><!-- /.navbar-collapse -->

  </div> <<!-- Fin-contenedor-->

</div><!-- /.container-fluid -->
</nav>

app/views/shared/_header_admin.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    

<div class="contenedor">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Adopta una mascota</a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

 
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Menu 1</a></li>
        <li><a href="#">Menu 2</a></li>
  
      

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-wrench"></i>&nbsp;Configuración</a>
           <ul class="dropdown-menu">
            <li>
              <%=link_to new_datos_personal_path do %>
                <i class="fa fa-user"></i>Datos personales          
              <%end%>
            </li> 
            <li>
              <%=link_to edit_usuario_registration_path do %>
                <i class="fa fa-key"></i>Modificar datos de acceso         
              <%end%>
            </li>   
            <li class="divider"></li> 
            <li>
              <%=link_to destroy_usuario_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>Salir
              <%end%>
            </li>
           </ul> 
        </li>        
      </ul>
    </div><!-- /.navbar-collapse -->

</div> <!-- Fin-contenedor-->

  </div><!-- /.container-fluid -->
</nav>